import ArgumentParser
import Foundation
import SemanticVersion

@main
struct SemanticVersionGenerator: ParsableCommand {
  static let configuration = CommandConfiguration(
    commandName: "SemanticVersionGenerator",
    abstract: "Generate Swift source code with semantic version from a version file",
    discussion: """
      This tool reads a version string from a file and generates Swift source code
      that defines a static property using the #semanticVersion macro.
      """,
  )

  @Option(name: .long, help: "Path to the version file")
  var versionFile: String

  @Option(name: .long, help: "Target name for the generated code")
  var targetName: String

  @Option(name: .long, help: "Output file path for the generated Swift code")
  var output: String

  func run() throws {
    // Read the version from the file and trim newlines only (don't parse)
    let versionString = try String(contentsOfFile: versionFile, encoding: .utf8).trimmingCharacters(in: .newlines)

    // Validate that we have a non-empty version string
    guard !versionString.isEmpty else { throw ValidationError("Version file '\(versionFile)' is empty") }

    // Generate the Swift source code
    let sourceCode = try generateSwiftCode(targetName: targetName, version: versionString)

    // Ensure the output directory exists
    let outputURL = URL(fileURLWithPath: output)
    let outputDirectory = outputURL.deletingLastPathComponent()
    try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true, attributes: nil)

    // Write the generated code to the output file
    try sourceCode.write(to: outputURL, atomically: true, encoding: .utf8)

    print("Generated version file: \(output)")
    print("Target: \(targetName)")
    print("Version: \(versionString)")
  }

  private func generateSwiftCode(targetName: String, version: String) throws -> String {
    let semanticVersion: SemanticVersion = try SemanticVersion.build(version)
    let params: [String] = [
      "\(String(semanticVersion.major))", "\(String(semanticVersion.minor))", "\(String(semanticVersion.patch))",
      "prereleaseIdentifiers: [\(semanticVersion.prereleaseIdentifiers.map { "\"\($0)\"" }.joined(separator: ", "))]",
      "buildMetadataIdentifiers: [\(semanticVersion.buildMetadataIdentifiers.map { "\"\($0)\"" }.joined(separator: ", "))]",
    ]

    return """
      // Generated by SemanticVersionPlugin
      // Do not edit this file manually

      import SemanticVersion

      /// Version information for the \(targetName) target
      extension TargetVersions {
        /// The semantic version of this target
        public static let \(versionVariableName(targetName)): SemanticVersion = .init(\(params.joined(separator: ", ")))
      }
      """
  }

  private func sanitizeTargetName(_ name: String) -> String {
    // Replace hyphens and spaces with underscores, capitalize first letter
    name.replacingOccurrences(of: "-", with: "_").replacingOccurrences(of: " ", with: "_")
      .replacingOccurrences(of: ".", with: "_")
  }

  private func versionVariableName(_ name: String) -> String {
    // Replace hyphens and spaces with underscores, capitalize first letter
    let sanitized = sanitizeTargetName(name)

    // Ensure it starts with a capital letter for enum name
    guard let first = sanitized.first else { return "Target" }
    return String(first).lowercased() + sanitized.dropFirst()
  }
}
