import ArgumentParser
import Foundation
import SemanticVersion

@main
struct SemanticVersionGenerator: ParsableCommand {
  static let configuration = CommandConfiguration(
    commandName: "SemanticVersionGenerator",
    abstract: "Generate Swift source code with semantic version from a version file",
    discussion: """
      This tool reads a version string from a file and generates Swift source code
      that defines a static property using the #semanticVersion macro.
      """,
  )

  @Option(name: .customLong("version-file"), help: "Path to the version file", transform: URL.init(fileURLWithPath:))
  var versionFileURL: URL

  @Option(name: .long, help: "Target name for the generated code")
  var targetName: String

  @Option(
    name: [.customLong("output"), .short],
    help: "Output file path for the generated Swift code",
    transform: URL.init(fileURLWithPath:)
  )
  var outputFileURL: URL

  var fileManager: FileManager { FileManager.default }

  func run() throws {
    if !fileManager.isReadableFile(atPath: versionFileURL.path(percentEncoded: false)) {
      throw ValidationError("Version file '\(versionFileURL)' is not readable")
    }

    // Read the version from the file and trim newlines only (don't parse)
    let versionString: String = try String(contentsOf: versionFileURL, encoding: .utf8)
      .trimmingCharacters(in: .newlines)

    // Validate that we have a non-empty version string
    guard !versionString.isEmpty else { throw ValidationError("Version file '\(versionFileURL)' is empty") }

    // Generate the Swift source code
    let sourceCode: String = try generateSwiftCode(targetName: targetName, version: versionString)

    // Ensure the output directory exists
    let outputDirectory: URL = outputFileURL.deletingLastPathComponent()
    try fileManager.createDirectory(at: outputDirectory, withIntermediateDirectories: true, attributes: nil)

    // Write the generated code to the output file
    try sourceCode.write(to: outputFileURL, atomically: true, encoding: .utf8)

    print("Generated version file: \(outputFileURL.path(percentEncoded: false)))")
    print("Target: \(targetName)")
    print("Version: \(versionString)")
  }

  private func generateSwiftCode(targetName: String, version: String) throws -> String {
    let semanticVersion: SemanticVersion = try SemanticVersion.build(version)

    return """
      // Generated by SemanticVersionPlugin
      // Do not edit this file manually

      import SemanticVersion

      extension TargetVersions {
        /// The version of the \(targetName) target.
        public static let \(versionVariableName(targetName)): SemanticVersion = \(semanticVersion.codeExpression)
      }
      """
  }

  private func sanitizeTargetName(_ name: String) -> String {
    // Replace hyphens and spaces with underscores, capitalize first letter
    name.replacingOccurrences(of: "-", with: "_").replacingOccurrences(of: " ", with: "_")
      .replacingOccurrences(of: ".", with: "_")
  }

  private func versionVariableName(_ name: String) -> String {
    // Replace hyphens and spaces with underscores, capitalize first letter
    let sanitized = sanitizeTargetName(name)

    // Ensure it starts with a capital letter for enum name
    guard let first = sanitized.first else { return "Target" }
    return String(first).lowercased() + sanitized.dropFirst()
  }
}
