version: 1
sourceConfigurations:
  op:
    vault: personal
secrets:
  TEST_MPCT_SECRET1_OP_ONLY:
    sources:
      op:
        item: "[TEST] mpct.import-secrets.shared-item"
        label: item1-secret
  TEST_MPCT_SECRET2_MULTILINE:
    sources:
      op:
        item: '[TEST] mpct.import-secrets.shared-item'
        label: item1-multiline
  TEST_MPCT_SECRET3_OP_AND_FAKE:
    sources:
      op:
        item: '[TEST] mpct.import-secrets.database-item'
        label: item2-secret
