#:schema ./schema/mise.json

# Minimum required mise version.
min_version = "2025.8.6"

[tools]
# https://app-updates.agilebits.com/product_history/CLI2
# CLI for 1Password.
# Used in the ImportSecrets library.
1password = "latest"

# https://github.com/apple/container/releases/
# Run Linux containers as lightweight virtual machines.
# Used in the mise `test-linux` task to run tests in Linux container while running on macOS.
container = "0.3.0"

# https://github.com/securevale/swift-confidential/releases/
# Obfuscation tool for Swift.
# Used in ObfuscateSecrets library.
"ubi:securevale/swift-confidential" = "latest"

# https://github.com/mvdan/sh/releases/
# Formats shell scripts.
# Used in the mise `format` task.
shfmt = "latest"

# https://github.com/koalaman/shellcheck/releases/
# Lints and formats shell scripts.
# Used on CI to lint shell scripts.
shellcheck = "latest"

[settings]
# Enables experimental features.
# Used for lockfile support.
experimental = true

# Use the .lock file for mise.
# This allows to lock tool versions and have flexibility in updating them,
# by not locking the exact version in the mise.toml file.
lockfile = true

# Use the idiomatic version files.
# Used for .ruby-version, .nvmrc, etc.
idiomatic_version_file = true

# A list of tools to install if there is an idiomatic version file.
# Don't put "swift" there, as it is managed by Xcode.
# Unless you want to use a custom version of Swift.
idiomatic_version_file_enable_tools = []

[tasks.test-linux]
description = "Run tests in Linux container"
run = "Scripts/tools/container/container.sh --test"

[tasks.test-linux-docker]
# Sometimes the `container` binary fails, and this task can be used as a fallback.
description = "Run tests in Linux container with Docker.app"
run = "Scripts/tools/docker/docker.sh --test"

[tasks.test-op]
description = "Integration test on macOS with 1Password"
run = "Scripts/tools/op/op.sh --test"

[tasks.lint]
description = "Lint source code"
run = """
Scripts/tools/swift-format/swift-format.sh --lint
Scripts/tools/shellcheck/shellcheck.sh --lint
"""

[tasks.format]
description = "Format source code"
run = """
Scripts/tools/swift-format/swift-format.sh --format
Scripts/tools/shellcheck/shellcheck.sh --format
Scripts/tools/shfmt/shfmt.sh --format
"""
