name: 'Select Swift Version'
description: 'Select Xcode version for Swift compilation'
inputs:
  xcode-version:
    description: 'Xcode version to select'
    required: true
  swift-version:
    description: 'Swift version to select'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Xcode
      # Select Xcode for swift and xcodebuild.
      # We need 6.1 swift and setup-swift@v2 is broken.
      if: ${{ inputs.xcode-version != '' && runner.os == 'macOS' }}
      shell: bash
      run: |
        sudo xcode-select -s "/Applications/Xcode_${XCODE_VERSION}.app"

        defaults write com.apple.dt.Xcode IDEPackageEnablePrebuilts YES
      env:
        XCODE_VERSION: ${{ inputs.xcode-version }}

    - name: Setup Swift (Linux)
      if: ${{ inputs.swift-version != '' && runner.os == 'Linux' }}
      uses: swift-actions/setup-swift@7d6348b84c07b33515ee21ebc40bbf974cc19d40
      with:
        swift-version: ${{ matrix.swift-version }}
