name: 'Prepare Swift'
description: 'Prepare Swift for compilation'
inputs:
  xcode-version:
    description: 'Xcode version to select'
    required: true
  swift-version:
    description: 'Swift version to select'
    required: true
  package-name:
    description: 'Package name to cache'
    required: true
  build-system:
    description: 'Build system to use'
    required: true
    default: 'swift'
  configuration:
    description: 'Configuration to use'
    required: true
    default: 'debug'
  architecture:
    description: 'Architecture to use'
    required: true
    default: ${{ runner.arch }}
  use-build-cache:
    description: 'Use build cache'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - name: Select Swift Version
      uses: ./.github/workflows/templates/select-swift-version/
      with:
        xcode-version: ${{ inputs.xcode-version }}
        swift-version: ${{ inputs.swift-version }}

    - name: Cache Swift Packages and Build Intermediate Files
      uses: ./.github/workflows/templates/swift-cache/
      with:
        package-name: ${{ inputs.package-name }}
        build-system: ${{ inputs.build-system }}
        swift-version: ${{ inputs.swift-version }}
        configuration: ${{ inputs.configuration }}
        xcode-version: ${{ inputs.xcode-version }}
        architecture: ${{ inputs.architecture }}
        use-build-cache: ${{ inputs.use-build-cache }}

    - name: Trust Swift Package Macros and Plugins
      uses: ./.github/workflows/templates/spm-trust/
