name: 'Prepare Swift'
description: 'Prepare Swift for compilation'
inputs:
  xcode-version:
    description: 'Xcode version to select'
    required: true
  swift-version:
    description: 'Swift version to select'
    required: true
  build-system:
    description: 'Build system to use'
    required: true
    default: 'swift'
  configuration:
    description: 'Configuration to use'
    required: true
    default: 'debug'
  architecture:
    description: 'Architecture to use'
    required: true
    default: ${{ runner.arch }}
  use-build-cache:
    description: 'Use build cache'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        # Install curl and zip if they are missing
        # This happens all the time in the swift container
        apt-get update

        if ! which curl > /dev/null 2>&1; then
          apt-get install -y curl
        fi

        if ! which zip > /dev/null 2>&1; then
          apt-get install -y zip
        fi

    - name: Empty mise.toml for Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        rm -rf mise.toml
        touch mise.toml

    - name: Install mise tools
      if: ${{ runner.os == 'Linux' }}
      uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566
      with:
        mise_toml: |
          [tools]
          shfmt = "latest"
          shellcheck = "latest"

    - name: Install mise tools
      if: ${{ runner.os != 'Linux' }}
      uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566

    - name: Select Swift Version
      uses: ./.github/workflows/templates/select-swift-version/
      with:
        xcode-version: ${{ inputs.xcode-version }}
        swift-version: ${{ inputs.swift-version }}

    - name: Cache Swift Packages and Build Intermediate Files
      uses: ./.github/workflows/templates/swift-cache/
      with:
        build-system: ${{ inputs.build-system }}
        swift-version: ${{ inputs.swift-version }}
        configuration: ${{ inputs.configuration }}
        xcode-version: ${{ inputs.xcode-version }}
        architecture: ${{ inputs.architecture }}
        use-build-cache: ${{ inputs.use-build-cache }}

    - name: Trust Swift Package Macros and Plugins
      uses: ./.github/workflows/templates/spm-trust/
