version: 1
sourceConfigurations:
  op:
    vault: personal
secrets:
  - prefix: TEST_OP_SHARED_ITEM_SINGLE_LABEL_
    sources:
      op:
        item: "[TEST] mpct.import-secrets.shared-item"
        labels:
          - item1-secret
  - prefix: TEST_OP_SHARED_ITEM_SINGLE_LABEL_MULTILINE_
    sources:
      op:
        item: '[TEST] mpct.import-secrets.shared-item'
        labels:
          - item1-multiline
  - prefix: TEST_OP_DATABASE_ITEM_
    sources:
      op:
        item: '[TEST] mpct.import-secrets.database-item'
        labels:
          - 'db password'
  - prefix: TEST_OP_SHARED_ITEM2_ALL_LABELS_
    sources:
      op:
        item: "[TEST] mpct.import-secrets.shared-item2"
  - prefix: TEST_OP_SHARED_ITEM2_ALL_LABELS_RENAMED_
    sources:
      op:
        item: "[TEST] mpct.import-secrets.shared-item2"
secretNamesMapping:
  TEST_OP_SHARED_ITEM2_ALL_LABELS_RENAMED_item2-secret: RENAMED_ITEM2_SECRET
  TEST_OP_SHARED_ITEM2_ALL_LABELS_RENAMED_item2-multiline: RENAMED_ITEM2_MULTILINE
