#:schema ./schema/mise.json

# CI settings.
[settings]
# Disable development tools that are not needed for CI.
disable_tools = ["container", "gitleaks", "hk", "pkl"]

# Disable caching of environment variables.
env_cache = false

[deps]
disable = ["git-bootstrap", "hk-install"]
